-- ============================================================================
-- 002_etl_sync_status.sql
--
-- Objetivo: dar ao dashboard uma forma confiável de saber "quando os dados
-- foram atualizados pela última vez", refletindo a execução real do ETL
-- (GitHub Actions) — não apenas a data de criação de algum registro.
--
-- Estratégia:
--   1. Uma tabela de log (`etl_sync_log`), somente para o ETL escrever
--      (INSERT) a cada execução (sucesso ou erro).
--   2. Uma view fina (`etl_sync_status`) que expõe só a última execução,
--      e é o único objeto liberado para leitura pública (`anon`).
--
-- Rode este script no SQL Editor do Supabase.
-- ============================================================================

create table if not exists privado.etl_sync_log (
  id bigint generated by default as identity primary key,
  executado_em timestamptz not null default now(),
  status text not null default 'sucesso' check (status in ('sucesso', 'erro')),
  linhas_processadas integer,
  detalhes text
);

comment on table privado.etl_sync_log is
  'Histórico de execuções do ETL (GitHub Actions) que popula o schema privado. '
  'Escrito exclusivamente pela pipeline (via credenciais próprias, não pela anon key).';

-- RLS habilitado por padrão de segurança, embora o acesso já seja
-- controlado via GRANT: nenhuma policy é criada para `anon`, então, mesmo
-- que um GRANT futuro seja adicionado por engano, a ausência de policy
-- bloqueia o acesso.
alter table privado.etl_sync_log enable row level security;

-- View pública: expõe apenas a execução mais recente, sem detalhes
-- internos (ex: mensagens de erro, contagens sensíveis).
create or replace view privado.etl_sync_status as
select executado_em, status
from privado.etl_sync_log
order by executado_em desc
limit 1;

-- Apenas a view fica acessível ao público — a tabela de log completa
-- (com histórico e detalhes de erro) permanece privada.
grant select on privado.etl_sync_status to anon;

-- Garante explicitamente que a tabela de log NÃO é legível pelo `anon`.
revoke all privileges on privado.etl_sync_log from anon;
